# remember to fill <account_id>
AWSTemplateFormatVersion: '2010-09-09'
Description: Resources needed to deploy scheduled lambda function with ECR image.
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: aws-lambda-training-weather-function-cloudformatted
      Description: A starter AWS Lambda function.
      Role: arn:aws:iam::<account_id>:role/aws-lambda-testing-role-cf
      PackageType: Image
      Code:
        ImageUri: <account_id>.dkr.ecr.eu-north-1.amazonaws.com/aws-lambda-testing-repository:latest
      Timeout: 30
      MemorySize: 128
      TracingConfig:
        Mode: Active
      # VpcConfig:
      #   SecurityGroupIds:
      #     - sg-<sg_id>
      #   SubnetIds:
      #     - subnet-<subnet_id_1>
      #     - subnet-<subnet_id_2>
  ScheduledRule:
    Type: AWS::Events::Rule
    DependsOn: LambdaFunction
    Properties:
      Name: aws-lambda-training-eventbridge-cloudformatted
      Description: "ScheduledRule"
      ScheduleExpression: "cron(00 12 ? * MON-FRI *)"
      State: "ENABLED"
      Targets:
        -
          Arn:
            Fn::GetAtt:
              - "LambdaFunction"
              - "Arn"
          Id: "TargetFunctionV1"
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    DependsOn: LambdaFunction
    Properties:
      FunctionName: !Ref "LambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRule"
          - "Arn"